<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>SpinePet</RootNamespace>
    <AssemblyName>SpinePet</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpineRuntime41\SpineRuntime41.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Tools\**\*"
             CopyToOutputDirectory="PreserveNewest"
             LinkBase="Tools\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\docs\CharacterNames.json"
                      LogicalName="SpinePet.Data.CharacterNames.json" />
  </ItemGroup>

</Project>
